const boardElement = document.getElementById('board');
const timerElement = document.getElementById('timer');
const mineCountElement = document.getElementById('mineCount');
const flagCountElement = document.getElementById('flagCount');
const statusElement = document.getElementById('status');
const flagButton = document.getElementById('flagButton');
const size = 10; const mineTotal = 40; let cells = []; let flags = 0; let started = false; let finished = false; let flagMode = false; let seconds = 0; let timerId;
function startGame() { clearInterval(timerId); cells = Array.from({ length: size * size }, (_, index) => ({ index, mine: false, revealed: false, flagged: false, adjacent: 0 })); const mineIndexes = new Set(); while (mineIndexes.size < mineTotal) mineIndexes.add(Math.floor(Math.random() * cells.length)); mineIndexes.forEach(index => { cells[index].mine = true; }); cells.forEach(cell => { cell.adjacent = neighbors(cell.index).filter(index => cells[index].mine).length; }); flags = 0; seconds = 0; started = false; finished = false; timerElement.textContent = '0'; statusElement.textContent = 'Find a safe first move.'; render(); }
function neighbors(index) { const row = Math.floor(index / size); const column = index % size; const result = []; for (let rowOffset = -1; rowOffset <= 1; rowOffset += 1) for (let columnOffset = -1; columnOffset <= 1; columnOffset += 1) { if (!rowOffset && !columnOffset) continue; const nextRow = row + rowOffset; const nextColumn = column + columnOffset; if (nextRow >= 0 && nextRow < size && nextColumn >= 0 && nextColumn < size) result.push(nextRow * size + nextColumn); } return result; }
function reveal(index) { if (finished || cells[index].revealed || cells[index].flagged) return; if (!started) { started = true; timerId = setInterval(() => { seconds += 1; timerElement.textContent = seconds; }, 1000); } const cell = cells[index]; cell.revealed = true; if (cell.mine) { finished = true; clearInterval(timerId); cells.filter(item => item.mine).forEach(item => { item.revealed = true; }); statusElement.textContent = 'Boom. Start a new field and try again.'; API.saveScore('minesweeper', seconds); render(); return; } if (!cell.adjacent) neighbors(index).forEach(reveal); if (cells.filter(item => !item.mine && !item.revealed).length === 0) { finished = true; clearInterval(timerId); statusElement.textContent = `Field clear in ${seconds}s. Nice work.`; API.saveScore('minesweeper', seconds); } render(); }
function toggleFlag(index) { if (finished || cells[index].revealed) return; if (!cells[index].flagged && flags >= mineTotal) return; cells[index].flagged = !cells[index].flagged; flags += cells[index].flagged ? 1 : -1; render(); }
function render() { boardElement.innerHTML = ''; cells.forEach(cell => { const button = document.createElement('button'); button.className = `cell ${cell.revealed ? 'revealed' : ''} ${cell.mine && cell.revealed ? 'mine' : ''} ${cell.flagged ? 'flagged' : ''} ${cell.adjacent ? `number-${cell.adjacent}` : ''}`; button.textContent = cell.flagged ? '!' : cell.revealed && cell.mine ? '*' : cell.revealed && cell.adjacent ? cell.adjacent : ''; button.setAttribute('aria-label', cell.flagged ? 'Flagged cell' : 'Minesweeper cell'); button.addEventListener('click', () => flagMode ? toggleFlag(cell.index) : reveal(cell.index)); button.addEventListener('contextmenu', event => { event.preventDefault(); toggleFlag(cell.index); }); boardElement.appendChild(button); }); flagCountElement.textContent = flags; mineCountElement.textContent = mineTotal - flags; }
document.getElementById('newButton').addEventListener('click', startGame); flagButton.addEventListener('click', () => { flagMode = !flagMode; flagButton.textContent = `FLAG MODE: ${flagMode ? 'ON' : 'OFF'}`; }); startGame();
